[global]
server_name = "${server_name}"
database_path = "/var/lib/matrix-conduit"
database_backend = "rocksdb"

port = 6167
address = "0.0.0.0"

allow_registration = ${allow_registration}
allow_federation = ${allow_federation}

# trusted_servers = ["matrix.org"]
